### ISSUE TITLE
"Cannot allocate memory" error

### ISSUE THREAD

**Issue by axel9546** [leoluk/paperlike-go#10]
Hi
I'm on debian, xfce.

```
lillo@MBPDebian:~$ ddcutil detect --verbose
Output level:               Verbose
Reporting DDC data errors:  false
Trace groups active:        none
Traced functions:           none
Traced files:               none
Force I2C slave address:    false
User defined features:      disabled

Performance and Retry Options:
   Deferred sleep enabled:                      false
   Sleep suppression (reduced sleeps) enabled:  false
   Dynamic sleep adjustment enabled:            false

No displays found
lillo@MBPDebian:~$ echo "SUBSYSTEM==\"i2c-dev\", GROUP=\"root\", MODE=\"0660\"" | sudo tee /etc/udev/rules.d/50-i2c.rules
SUBSYSTEM=="i2c-dev", GROUP="your-group-here", MODE="0660"
lillo@MBPDebian:~$ sudo udevadm trigger
Failed to write 'change' to '/sys/devices/virtual/input/input18/uevent': Cannot allocate memory
lillo@MBPDebian:~$ 

```

**Comment by leoluk** [comment]
Might be this udev/kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=207695

**Comment by leoluk** [comment]
As a workaround, I suppose you could just chown the /dev/i2c-* file.

**Comment by axel9546** [comment]
> Might be this udev/kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=207695

Thanks! 
I do not understand how to implement that patch. What should I do in order to make it work? :) (sorry for being a noob)

**Comment by leoluk** [comment]
Do you happen to have the `ckb-next-daemon` daemon running? According to the bug report, it's a likely culprit. Other than that, you'd have to wait for the bug to be fixed and the fix to make it to Debian stable (or whatever you're using).

**Comment by axel9546** [comment]
> Do you happen to have the `ckb-next-daemon` daemon running? 

How do I check is running?

Btw my goal was to have the dasung paperlike hd f backlight disabled by default when connected. You know the annoying backlight flash :)

**Comment by leoluk** [comment]
`ps faux | grep ckb-next`

And make sure that the `/etc/udev/rules.d/50-i2c.rules` file contains your actual group instead of `your-group-here` or it won't work. Does the display show up at all when you run `sudo ddcutil detect --verbose`?

What's the output of `xrandr`?

**Comment by axel9546** [comment]
> ps faux | grep ckb-next


`lillo       3473  0.0  0.0   6260   648 pts/0    S+   16:13   0:00          |           \_ grep ckb-next`



> sudo ddcutil detect --verbose
```

Output level:               Verbose
Reporting DDC data errors:  false
Trace groups active:        none
Traced functions:           none
Traced files:               none
Force I2C slave address:    false
User defined features:      disabled

Performance and Retry Options:
   Deferred sleep enabled:                      false
   Sleep suppression (reduced sleeps) enabled:  false
   Dynamic sleep adjustment enabled:            false

No displays found

```

**Comment by jtbg** [comment]
What's the output of `sudo ddcutil environment`?
