### ISSUE TITLE
Get the current value?

### ISSUE THREAD

**Issue by Revilotom** [leoluk/paperlike-go#8]
Would it be possible to for example get the current contrast?
I wondering because I would like to bind a key to increase contrast instead of having to specify the exact contrast level...

**Comment by leoluk** [comment]
I do not believe there is a way to get that information from the device. Would be easy enough to cache it, though.

**Comment by Revilotom** [comment]
Thanks for the reply! I don't have any experience with i2c programming so was not sure if this was something that could be got from the device itself.
